name: pag_web
description: "A new Flutter plugin project."
version: 1.0.0
homepage:

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.0.0
  pag_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    implements: pag_flutter
    platforms:
      web:
        pluginClass: PAGWebPlugin
        fileName: pag_web.dart
